using Qyl.DurableAgents.Generators.Models;

namespace Qyl.DurableAgents.Generators.Emitters;

internal static class DurableHostEmitter
{
    public static string Emit(
        EquatableArray<OrchestratorEntry> orchestrators,
        EquatableArray<ActivityEntry> activities,
        EquatableArray<AgentEndpointEntry> endpoints)
    {
        if (orchestrators.IsEmpty && activities.IsEmpty && endpoints.IsEmpty)
            return string.Empty;

        var orchestratorList = orchestrators
            .OrderBy(static e => e.TaskName, StringComparer.Ordinal)
            .ToArray();
        var activityList = activities
            .OrderBy(static e => e.TaskName, StringComparer.Ordinal)
            .ToArray();
        var endpointList = endpoints
            .OrderBy(static e => e.Route, StringComparer.Ordinal)
            .ThenBy(static e => e.HttpMethod, StringComparer.Ordinal)
            .ToArray();

        var sb = new IndentedStringBuilder();
        sb.AppendLineNoIndent("// <auto-generated/>");
        sb.AppendLineNoIndent("#nullable enable");
        sb.AppendLineNoIndent("#pragma warning disable");
        sb.AppendLine();
        // Required for extension-call resolution: AddTasks lives in
        // Microsoft.DurableTask.Worker, UseGrpc on the worker side lives in
        // Microsoft.DurableTask.Worker.Grpc, and UseGrpc on the client side lives
        // in Microsoft.DurableTask.Client.Grpc. All three declare a type literally
        // named DurableTaskWorkerBuilderExtensions / DurableTaskClientBuilderExtensions,
        // so we resolve via extension-method syntax instead of qualifying the
        // static type — assembly identity disambiguates per call.
        sb.AppendLineNoIndent("using global::Microsoft.DurableTask.Worker;");
        sb.AppendLineNoIndent("using global::Microsoft.DurableTask.Client;");
        sb.AppendLine();

        using (sb.BeginNamespace("Qyl.DurableAgents.Generated"))
        using (sb.BeginClass("internal static", "QylDurableHost"))
        {
            EmitAddQylDurableAgents(sb, orchestratorList, activityList);
            sb.AppendLine();
            EmitMapQylAgentEndpoints(sb, endpointList);
        }

        return sb.ToString();
    }

    private static void EmitAddQylDurableAgents(
        IndentedStringBuilder sb,
        OrchestratorEntry[] orchestrators,
        ActivityEntry[] activities)
    {
        sb.AppendLine(
            "public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddQylDurableAgents(");
        sb.AppendLine(
            "    this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        sb.AppendLine(
            "    global::System.Action<global::Microsoft.Agents.AI.DurableTask.DurableAgentsOptions>? configure = null)");
        using (sb.BeginBlock())
        {
            sb.AppendLine(
                "global::Microsoft.Agents.AI.DurableTask.ServiceCollectionExtensions.ConfigureDurableAgents(");
            sb.AppendLine("    services,");
            sb.AppendLine("    options => configure?.Invoke(options),");
            sb.AppendLine("    workerBuilder =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine("workerBuilder.AddTasks(registry =>");
                using (sb.BeginBlock())
                {
                    foreach (var orch in orchestrators)
                        EmitOrchestratorRegistration(sb, orch);
                    foreach (var act in activities)
                        EmitActivityRegistration(sb, act);
                }

                sb.AppendLine(");");
                sb.AppendLine("workerBuilder.UseGrpc();");
            }

            sb.AppendLine(",");
            sb.AppendLine("    clientBuilder =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine("clientBuilder.UseGrpc();");
            }

            sb.AppendLine(");");
            sb.AppendLine();
            sb.AppendLine("return services;");
        }
    }

    private static void EmitOrchestratorRegistration(IndentedStringBuilder sb, OrchestratorEntry orch)
    {
        var inputType = orch.InputTypeFullyQualifiedName ?? "global::System.ValueTuple";
        var outputType = orch.OutputTypeFullyQualifiedName;

        sb.AppendLine($"registry.AddOrchestratorFunc<{inputType}, {outputType}>(");
        sb.AppendLine($"    {StringLiteral(orch.TaskName)},");

        if (orch.InputTypeFullyQualifiedName is null)
        {
            if (orch.ReturnsTask)
                sb.AppendLine($"    static (ctx, _) => {orch.DeclaringTypeFullyQualifiedName}.{orch.MethodName}(ctx));");
            else
                sb.AppendLine($"    static (ctx, _) => global::System.Threading.Tasks.Task.FromResult({orch.DeclaringTypeFullyQualifiedName}.{orch.MethodName}(ctx)));");
        }
        else
        {
            if (orch.ReturnsTask)
                sb.AppendLine($"    static (ctx, input) => {orch.DeclaringTypeFullyQualifiedName}.{orch.MethodName}(ctx, input));");
            else
                sb.AppendLine($"    static (ctx, input) => global::System.Threading.Tasks.Task.FromResult({orch.DeclaringTypeFullyQualifiedName}.{orch.MethodName}(ctx, input)));");
        }
    }

    private static void EmitActivityRegistration(IndentedStringBuilder sb, ActivityEntry act)
    {
        var inputType = act.InputTypeFullyQualifiedName ?? "global::System.ValueTuple";
        var outputType = act.ReturnsVoid ? "global::System.ValueTuple" : act.OutputTypeFullyQualifiedName;

        sb.AppendLine($"registry.AddActivityFunc<{inputType}, {outputType}>(");
        sb.AppendLine($"    {StringLiteral(act.TaskName)},");

        var call = BuildActivityCall(act);

        if (act.ReturnsVoid && act.ReturnsTask)
        {
            sb.AppendLine("    static async (ctx, input) =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine($"await {call}.ConfigureAwait(false);");
                sb.AppendLine("return default(global::System.ValueTuple);");
            }
            sb.AppendLine(");");
        }
        else if (act.ReturnsVoid)
        {
            sb.AppendLine("    static (ctx, input) =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine($"{call};");
                sb.AppendLine("return global::System.Threading.Tasks.Task.FromResult(default(global::System.ValueTuple));");
            }
            sb.AppendLine(");");
        }
        else if (act.ReturnsTask)
        {
            sb.AppendLine($"    static (ctx, input) => {call});");
        }
        else
        {
            sb.AppendLine($"    static (ctx, input) => global::System.Threading.Tasks.Task.FromResult({call}));");
        }
    }

    private static string BuildActivityCall(ActivityEntry act)
    {
        var prefix = $"{act.DeclaringTypeFullyQualifiedName}.{act.MethodName}";
        return act.ParameterShape switch
        {
            ActivityParameterShape.None => $"{prefix}()",
            ActivityParameterShape.ContextOnly => $"{prefix}(ctx)",
            ActivityParameterShape.InputOnly => $"{prefix}(input)",
            ActivityParameterShape.InputThenContext => $"{prefix}(input, ctx)",
            ActivityParameterShape.ContextThenInput => $"{prefix}(ctx, input)",
            _ => $"{prefix}(input)"
        };
    }

    private static void EmitMapQylAgentEndpoints(IndentedStringBuilder sb, AgentEndpointEntry[] endpoints)
    {
        sb.AppendLine(
            "public static global::Microsoft.AspNetCore.Builder.WebApplication MapQylAgentEndpoints(");
        sb.AppendLine("    this global::Microsoft.AspNetCore.Builder.WebApplication app)");
        using (sb.BeginBlock())
        {
            foreach (var ep in endpoints)
                EmitEndpoint(sb, ep);

            sb.AppendLine("return app;");
        }
    }

    private static void EmitEndpoint(IndentedStringBuilder sb, AgentEndpointEntry ep)
    {
        var mapMethod = ep.HttpMethod switch
        {
            "GET" => "MapGet",
            "POST" => "MapPost",
            "PUT" => "MapPut",
            "DELETE" => "MapDelete",
            "PATCH" => "MapPatch",
            _ => "MapPost"
        };

        sb.AppendLine(
            $"global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.{mapMethod}(");
        sb.AppendLine("    app,");
        sb.AppendLine($"    {StringLiteral(ep.Route)},");

        if (ep.InputTypeFullyQualifiedName is null)
        {
            sb.AppendLine(
                "    static async (global::Microsoft.DurableTask.Client.DurableTaskClient client, global::System.Threading.CancellationToken cancellationToken) =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine(
                    $"var instanceId = await client.ScheduleNewOrchestrationInstanceAsync({StringLiteral(ep.OrchestratorName)}, cancellation: cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("return global::Microsoft.AspNetCore.Http.Results.Accepted($\"/instances/{instanceId}\", new { instanceId });");
            }
            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine(
                $"    static async ({ep.InputTypeFullyQualifiedName} input, global::Microsoft.DurableTask.Client.DurableTaskClient client, global::System.Threading.CancellationToken cancellationToken) =>");
            using (sb.BeginBlock())
            {
                sb.AppendLine(
                    $"var instanceId = await client.ScheduleNewOrchestrationInstanceAsync({StringLiteral(ep.OrchestratorName)}, input, cancellationToken).ConfigureAwait(false);");
                sb.AppendLine("return global::Microsoft.AspNetCore.Http.Results.Accepted($\"/instances/{instanceId}\", new { instanceId });");
            }
            sb.AppendLine(");");
        }
    }

    private static string StringLiteral(string value) =>
        "\"" + value
            .ReplaceOrdinal("\\", @"\\")
            .ReplaceOrdinal("\"", "\\\"")
            .ReplaceOrdinal("\r", "\\r")
            .ReplaceOrdinal("\n", "\\n") + "\"";
}
